### ISSUE TITLE
0.73的oc有更新吗？usb定制通用不？我也是有雷电接口的

### ISSUE THREAD

**Issue by woodencow** [isoulgh/isoul-Hackintosh-EFI-Dell-G3-3579-OpenCore#1]

**Comment by isoulgh** [comment]
是通用的，在我电脑上正常使用。

**Comment by isoulgh** [comment]
稍后我更新一下oc版本到0.7.4

**Comment by isoulgh** [comment]
已更新🤝

**Comment by woodencow** [comment]
> 已更新🤝

谢谢！我本来想装11.6的0.7.3。

**Comment by woodencow** [comment]
qq:49214835 方便的话交流一下，需要setup_var 关闭Cfg lock吗？显卡缓存调到64mb还是128mb？我都不知道怎么引导进grub shell

**Comment by isoulgh** [comment]
不用管cfg，oc引导里有。
如果是同型号的机器，不用设置呀，直接就可以使用。
如果要进grub，那就需要加一个Tool。
