### ISSUE TITLE
使用你的EFI无法识别windows系统，直接就进去mac了。

### ISSUE THREAD

**Issue by jiaocoll** [isoulgh/isoul-Hackintosh-EFI-Dell-G3-3579-OpenCore#2]

**Comment by isoulgh** [comment]
按照你的描述，oc引导在你的电脑上应该默认引导启动了macos的系统。
可以编辑oc的配置文件，使启动时显示引导菜单，这样就可以选择需要启动的系统。

**Comment by isoulgh** [comment]
如果你配置正确的话，也可以像我这样，使用macos的系统偏好设置中的启动磁盘项，选择windows并重新启动来进入windows
![image](https://user-images.githubusercontent.com/47737022/167058608-266f272c-6699-4e5a-b413-c7ef738734fa.png)

**Comment by jiaocoll** [comment]
好的，谢谢。
