### ISSUE TITLE
安装时卡代码

### ISSUE THREAD

**Issue by Gseventeen17** [isoulgh/isoul-Hackintosh-EFI-Dell-G3-3579-OpenCore#4]
你好，几天前在安装13的时候反复卡这个代码，搜索了很多内容没有解决，请问这个是什么问题呢？是因为我的固态硬盘不兼容吗？大佬是否有头绪呢？
![FDD747D7-EAEF-4C4C-A514-ACB610F7E50C](https://user-images.githubusercontent.com/93527264/200222985-4c13fdbc-1c7d-40a1-a104-64499bae58b5.jpeg)

**Comment by isoulgh** [comment]
是和我一样的机型吗？固态硬盘是啥？使用最新发布的EFI了嘛？

**Comment by Gseventeen17** [comment]
固态硬盘是致钛tiplus5000，应该是硬盘的问题，最近买了个新的再试试
