### ISSUE TITLE
感谢开源，请问您说的TB口是什么

### ISSUE THREAD

**Issue by huoher** [isoulgh/isoul-Hackintosh-EFI-Dell-G3-3579-OpenCore#5]
感谢开源，请问您说的TB口是什么，可以使用外接显示器工作的
多谢百忙之中给予指点

**Comment by Gseventeen17** [comment]
应该是雷电口吧，type-c

**Comment by isoulgh** [comment]
> 感谢开源，请问您说的TB口是什么，可以使用外接显示器工作的
> 多谢百忙之中给予指点

楼上说的是对的，就是指雷电口，可以借助转接器（typec转HDMI等）来使用外接显示器
